import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>PORTFOLIOO!!!!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <div className={styles.ctas}>
            <a
              className={styles.primary}
              href="https://rotatingsandwiches.com/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Site under construction (Transitioning to Next.js) - check back soon!
            </a>
          </div>
        </main>
        <footer className={styles.footer}>
          <a
            href="https://crouton.net/"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/globe.svg"
              alt="Globe icon"
              width={16}
              height={16}
            />
            Go see crouton
          </a>
        </footer>
      </div>
    </>
  );
}
